apiVersion: apps/v1
metadata: 
  name: first-deploy
kind: Deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      application: nginx
  template:
    metadata:
      labels:
        application: nginx
    spec:
      containers:
        - name: nginx
          image: nginx