apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-deploy
spec:
  selector:
    matchLabels:
      application: nginx
  template:
    metadata:
      labels:
        application: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.27.2
          ports:
            - name: http
              containerPort: 80
          # resources:
          #   requests:
          #     memory: "100Mi"
          #     cpu: "100m"   # 1 vCPU = 1000m
          #   limits:
          #     memory: "1Gi"
          #     cpu: "500m"
---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: first-hpa
  labels:
    app: first-hpa
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: first-deploy
  metrics: 
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 20
    - type: Pods
      pods:
        metric:
          name: packets-per-second
        target:
          type: AverageValue
          averageValue: 1k
    # - type: Resource
    #   resource:
    #     name: memory
    #     targetAverageUtilization: 50
  # targetCPUUtilizationPercentage: 50