apiVersion: v1
kind: Pod
metadata:
  name: devops-testing-v2
spec:
  containers:
    - name: nginx
      image: nginx:latest
    - name: busybox
      image: busybox:latest
      command:
        - sh
        - c
        - "echo I am busybox && sleep 120"
      restartPolicy: Always