apiVersion: v1
kind: Pod
metadata:
  name: first-deploy
spec:
  nodeSelector: 
        kubernetes.io/hostname: devops-control-plane
  containers:
    - name: nginx
      image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: first-deploy-pod-2
spec:
  nodeSelector: 
    performance: high
  containers:
    - name: nginx
      image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: first-deploy-pod-03
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
            - key: performance
              operator: In
              values: 
                - high
      # preferredDuringSchedulingIgnoredDuringExecution:
  containers:
    - name: nginx
      image: nginx
