---
# tasks file for roles/docker
- name: Basic Playbook
  hosts: localhost # can be other hosts #all
  become: true # to run as root
  gather_facts: false 
  # vars:
  #   ansible_user: nayems
  vars_files:
    - vars
  tasks:
    # - name: Create a directory
    #   file:
    #     path: /tmp/testdir
    #     state: directory
    #     mode: '0644'
    - name: Print ansible user name
      debug:
        msg: "The current user is {{ ansible_user }}"

    # - name: Create a file in the directory
    #   file:
    #     path: /tmp/testdir/testfile.txt
    #     state: touch
    # - name : Update package manager file
    #   apt:
    #     update_cache: yes
    # - name : Ensure multiple packages are installed
    #   package:
    #     name:
    #       - nginx
    #       - git
    #       - curl
    #     state: present #absent
    # - name : check current director
    #   command: ls